// Rendered HATax against the live local MFA fixture; no mocked API routes.
// Receive disposable fixture credentials through stdin only. Never persist browser state.
const {chromium}=require(process.env.HA_PLAYWRIGHT_MODULE || 'C:/Users/mitch/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
let stage='startup';
(async()=>{
  const started=performance.now();
  let raw='';for await(const chunk of process.stdin)raw+=chunk;
  const fixture=JSON.parse(raw);raw='';
  assert.equal(fixture.origin,'https://127.0.0.1:8844');
  const browser=await chromium.launch({channel:'msedge',headless:true});
  try{
    // The disposable certificate is self-signed. Protocol verification runs
    // separately with an explicitly trusted CA; this browser probe does not
    // provide browser certificate-trust evidence.
    const context=await browser.newContext({ignoreHTTPSErrors:true});
    const page=await context.newPage();const errors=[];
    page.on('pageerror',()=>errors.push('page error'));
    stage='public-home';
    await page.goto(fixture.origin+'/');
    await page.locator('nav [data-open-previews]').click();
    await page.waitForFunction(()=>document.querySelector('#preview-dialog [data-books-link]').getAttribute('href')==='/connected.html');
    await page.locator('#preview-dialog [data-books-link]').click();
    await page.locator('#login-panel').waitFor({state:'visible'});
    assert.equal(await page.locator('#workspace').isVisible(),false);
    await page.locator('#login-panel a[href="/api/auth/login"]').click();
    stage='browser-password';
    stage='password-wait';
    await page.locator('[name=password]').waitFor();
    stage='password-action';
    const loginAction=new URL(await page.locator('form').first().getAttribute('action'),page.url());
    assert.equal(loginAction.origin,'https://127.0.0.1:8843');
    assert.ok(loginAction.pathname.startsWith('/realms/ha/login-actions/'));
    stage='username-fill';
    await page.locator('[name=username]').fill('ha-fictional-mfa');
    stage='password-fill';
    await page.locator('[name=password]').fill(fixture.password);fixture.password='';
    stage='password-submit';
    await page.locator('input[type=submit],button[type=submit]').first().click();
    stage='browser-otp';
    await page.locator('[name=otp]').waitFor();
    const otpAction=new URL(await page.locator('form').first().getAttribute('action'),page.url());
    assert.equal(otpAction.origin,'https://127.0.0.1:8843');
    assert.ok(otpAction.pathname.startsWith('/realms/ha/login-actions/'));
    const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));
    const digest=require('node:crypto').createHmac('sha1',fixture.secret).update(counter).digest();
    fixture.secret='';
    const offset=digest[digest.length-1]&15;
    const otp=String((digest.readUInt32BE(offset)&0x7fffffff)%1000000).padStart(6,'0');
    await page.locator('[name=otp]').fill(otp);
    await page.locator('input[type=submit],button[type=submit]').first().click();
    await page.waitForURL(fixture.origin+'/connected.html');
    const session=(await context.cookies(fixture.origin)).find(cookie=>cookie.name==='__Host-ha_session');
    assert.ok(session&&session.secure&&session.httpOnly&&session.path==='/'&&session.sameSite==='Lax');
    stage='books-open';
    await page.goto(fixture.origin+'/connected.html');
    await page.locator('#workspace').waitFor({state:'visible'});
    await page.waitForFunction(()=>document.querySelector('#case-choice').options.length===2);
    assert.equal(await page.locator('#case-choice option').count(),2);
    await page.locator('#case-choice').selectOption({index:1});
    await page.locator('#case-open').click();
    await page.waitForFunction(()=>document.querySelector('#document-list').children.length===4);
    stage='book-totals';
    assert.equal(await page.locator('#income').innerText(),'$1,500.00');
    assert.equal(await page.locator('#expenses').innerText(),'$320.00');
    assert.equal(await page.locator('#profit').innerText(),'$1,180.00');
    assert.match(await page.locator('#payments').innerText(),/recorded: \$100\.00.*confirmed: \$0\.00/);
    assert.match(await page.locator('#review-list').innerText(),/advertising:.*supporting document changed/);
    stage='reserve-choice';
    const revisionBeforeReserve=await page.locator('#revision').innerText();
    assert.equal(await page.locator('#reserve-total').innerText(),'$375.00');
    assert.equal(await page.locator('#reserve-extra-dollars').isEnabled(),false);
    await page.locator('#reserve-percent').fill('17.25');
    await page.locator('#reserve-extra-choice').selectOption('yes');
    await page.locator('#reserve-extra-dollars').fill('10.01');
    const reserveUpdated=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/connected/draft');
    await page.locator('#reserve-form button').click();
    assert.equal((await reserveUpdated).status(),200);
    await page.waitForFunction(()=>document.querySelector('#reserve-total').textContent==='$268.76');
    assert.equal(await page.locator('#reserve-base').innerText(),'$258.75');
    assert.equal(await page.locator('#reserve-extra').innerText(),'$10.01');
    assert.equal(await page.locator('#revision').innerText(),revisionBeforeReserve);
    assert.equal(await page.locator('#profit').innerText(),'$1,180.00');
    assert.match(await page.locator('#payments').innerText(),/recorded: \$100\.00.*confirmed: \$0\.00/);
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    const reserveScreenshot=require('node:path').resolve(__dirname,'../output/reserve-choice.png');
    require('node:fs').mkdirSync(require('node:path').dirname(reserveScreenshot),{recursive:true});
    await page.locator('#reserve-plan').screenshot({path:reserveScreenshot});
    await page.setViewportSize({width:1280,height:900});
    stage='record-confirmation-save';
    await page.locator('#confirmation-through').waitFor({state:'visible'});
    await page.waitForFunction(()=>!document.querySelector('#confirmation-choice').disabled);
    assert.equal(await page.locator('#confirmation-save').isEnabled(),false);
    await page.locator('#confirmation-through').fill('2026-10-03');
    await page.locator('#confirmation-reason').fill('Compared fictional card and cash entries with my records');
    await page.locator('#confirmation-choice').check();
    const confirmed=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/connected/records/confirmations'&&r.request().method()==='POST');
    await page.locator('#confirmation-save').click();assert.equal((await confirmed).status(),201);
    await page.waitForFunction(()=>document.querySelector('#confirmation-status').textContent.includes('Review statement is recorded'));
    assert.equal(await page.locator('#confirmation-history li').count(),1);
    assert.equal(await page.locator('#confirmation-choice').isChecked(),false);
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    const screenshotPath=require('node:path').resolve(__dirname,'../output/record-confirmation.png');
    require('node:fs').mkdirSync(require('node:path').dirname(screenshotPath),{recursive:true});
    await page.locator('#record-confirmation').screenshot({path:screenshotPath});
    await page.setViewportSize({width:1280,height:900});
    stage='period-totals';
    for(const period of ['month','quarter','year']){
      await page.locator('#period').selectOption(period);
      const updated=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/connected/draft');
      await page.locator('#period-form button').click();
      const response=await updated;assert.equal(response.status(),200);
      assert.equal((await response.json()).book_profit_minor,118000);
      await page.waitForLoadState('networkidle');
      assert.equal(await page.locator('#profit').innerText(),'$1,180.00');
      assert.equal(await page.locator('#expenses').innerText(),'$320.00');
      assert.equal(await page.locator('#reserve-total').innerText(),'$268.76');
    }
    stage='reserve-choice';
    await page.locator('#reserve-extra-choice').selectOption('no');
    assert.equal(await page.locator('#reserve-extra-dollars').inputValue(),'');
    await page.locator('#reserve-form button').click();
    await page.waitForFunction(()=>document.querySelector('#reserve-total').textContent==='$258.75');
    await page.locator('#reserve-percent').fill('25');
    await page.locator('#reserve-form button').click();
    await page.waitForFunction(()=>document.querySelector('#reserve-total').textContent==='$375.00');
    stage='payment-correction-save';
    await page.locator('#entry-history li[data-entry="owner-estimate"]').getByRole('button',{name:'Correct this entry'}).click();
    assert.equal(await page.locator('#entry-form [name=amount]').inputValue(),'100.00');
    await page.locator('#entry-form [name=amount]').fill('125.00');
    await page.locator('#entry-form [name=reason]').fill('Correct fictional recorded payment amount');
    const paymentSaved=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/connected/events'&&r.request().method()==='POST');
    await page.locator('#entry-form button').click();const paymentResponse=await paymentSaved;assert.equal(paymentResponse.status(),201);const paymentId=(await paymentResponse.json()).id;
    await page.waitForFunction(()=>document.querySelector('#payments').textContent.includes('recorded: $125.00'));
    stage='record-confirmation-stale';
    await page.waitForFunction(()=>document.querySelector('#confirmation-status').textContent.includes('Entries changed after'));
    assert.equal(await page.locator('#confirmation-history li').count(),1);
    stage='payment-correction-reopen';
    const paymentHistory=await(await context.request.get(fixture.origin+'/api/connected/events?profile=orchard&business=business&year=2026')).json();
    const priorPayment=paymentHistory.events.find(entry=>entry.id==='owner-estimate'),correctedPayment=paymentHistory.events.find(entry=>entry.id===paymentId);
    assert.equal(priorPayment.amount_minor,10000);assert.equal(priorPayment.status,'recorded_unverified');
    assert.equal(correctedPayment.amount_minor,12500);assert.equal(correctedPayment.status,'recorded_unverified');assert.equal(correctedPayment.government_confirmation,null);assert.equal(correctedPayment.posting_date,priorPayment.posting_date);
    assert.match(await page.locator('#payments').innerText(),/recorded: \$125\.00.*confirmed: \$0\.00/);
    assert.equal(await page.locator('#profit').innerText(),'$1,180.00');
    stage='cash-explanation-save';
    await page.locator('#entry-history li[data-entry="sale-cash"]').getByRole('button',{name:'Correct this entry'}).click();
    assert.equal(await page.locator('#entry-form [name=amount]').inputValue(),'500.00');
    await page.locator('#entry-explanation-mode').selectOption('replace');
    await page.locator('#entry-explanation').fill('Fictional browser cash clarification');
    await page.locator('#entry-form [name=reason]').fill('Clarify the recorded cash sales');
    const cashSaved=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/connected/events'&&r.request().method()==='POST');
    await page.locator('#entry-form button').click();const cashResponse=await cashSaved;assert.equal(cashResponse.status(),201);const cashId=(await cashResponse.json()).id;
    await page.waitForFunction(id=>document.querySelector('#entry-history li[data-entry="'+id+'"]')!==null,cashId);
    stage='cash-explanation-reopen';
    const events=await(await context.request.get(fixture.origin+'/api/connected/events?profile=orchard&business=business&year=2026')).json();
    const originalCash=events.events.find(entry=>entry.id==='sale-cash'),newCash=events.events.find(entry=>entry.id===cashId);
    assert.equal(originalCash.explanation,'Aggregate fictional market sales');assert.equal(newCash.explanation,'Fictional browser cash clarification');assert.equal(newCash.amount_minor,50000);assert.equal(newCash.posting_date,originalCash.posting_date);assert.equal(newCash.method,'cash');
    await page.waitForLoadState('networkidle');assert.equal(await page.locator('#profit').innerText(),'$1,180.00');
    stage='document-download';
    const receiptRow=page.locator('#document-list li').filter({has:page.locator('button')}).filter({hasText:fixture.document}).filter({hasText:'Current version'});
    assert.equal(await receiptRow.count(),1);
    stage='support-document-select';
    assert.ok((await page.locator('#support-document option').evaluateAll(options=>options.map(option=>option.value))).includes(JSON.stringify([fixture.document,fixture.version])));
    await page.locator('#support-document').selectOption(JSON.stringify([fixture.document,fixture.version]));
    for(const [downloadStage,button] of [['document-list-download',receiptRow.getByRole('button',{name:'Download this version'})],['support-document-download',page.locator('#support-download')]]){
      stage=downloadStage;
      const download=page.waitForEvent('download');await button.click();
      const stream=await (await download).createReadStream();let bytes=[];
      for await(const chunk of stream)bytes.push(chunk);
      assert.equal(Buffer.concat(bytes).toString(),'Fictional receipt correction');
    }
    stage='document-correction-choice';
    await receiptRow.getByRole('button',{name:'Add a corrected version'}).click();
    assert.equal(await page.locator('#document-mode').inputValue(),'correction');
    assert.equal(await page.locator('#correction-document').inputValue(),fixture.document);
    assert.equal(await page.locator('#correction-reason').inputValue(),'');
    assert.equal(await page.locator('#document-form [name=file]').inputValue(),'');
    stage='entry-correction-choice';
    await page.locator('#entry-history').getByRole('button',{name:'Correct this entry'}).first().click();
    assert.equal(await page.locator('#entry-form [name=kind]').inputValue(),'correction');
    assert.ok(await page.locator('#entry-form [name=replaces]').inputValue());
    assert.equal(await page.locator('#entry-form [name=reason]').inputValue(),'');
    assert.equal(await page.locator('#entry-form [name=method]').isDisabled(),true);
    stage='foreign-scope';
    await page.locator('#manual-scope summary').click();
    await page.locator('#scope-form [name=profile]').fill('cedar');
    await page.locator('#scope-form [name=business]').fill('cedar-business');
    await page.locator('#scope-form button').click();
    await page.waitForFunction(()=>document.querySelector('#status').textContent==='Resource unavailable');
    assert.equal(await page.locator('#profit').innerText(),'\u2014');
    assert.equal(await page.locator('#document-list li').count(),0);
    assert.equal(await page.locator('#entry-history li').count(),0);
    assert.equal(await page.locator('#confirmation-history li').count(),0);
    assert.equal(await page.locator('#reserve-percent').inputValue(),'25');
    assert.equal(await page.locator('#reserve-extra-choice').inputValue(),'no');
    assert.equal(await page.locator('#reserve-extra-dollars').inputValue(),'');
    assert.equal(await page.locator('#reserve-total').innerText(),'—');
    assert.equal(await page.locator('#confirmation-choice').isDisabled(),true);
    assert.equal(await page.locator('#confirmation-choice').isChecked(),false);
    assert.equal(await page.locator('#confirmation-through').inputValue(),'');
    assert.equal(await page.locator('#confirmation-reason').inputValue(),'');
    assert.equal(await page.locator('#entry-form [name=method]').isDisabled(),false);
    await page.locator('#scope-form [name=profile]').fill('orchard');
    await page.locator('#scope-form [name=business]').fill('business');
    await page.locator('#scope-form button').click();
    await page.waitForFunction(()=>document.querySelector('#document-list').children.length===4);
    stage='tax-handoff';
    await page.locator('#open-hatax').click();
    assert.equal(new URL(page.url()).pathname,'/tax');
    stage='tax-reopen';
    await page.locator('#tax-saving').waitFor({state:'visible'});
    await page.waitForFunction(()=>!document.querySelector('#reopen-input').disabled);
    assert.equal(await page.locator('#save-input').isDisabled(),true);
    await page.locator('#reopen-input').click();
    await page.waitForFunction(()=>document.querySelector('[name=firstName]')?.value==='Fictional tax corrected');
    stage='tax-save';
    await page.locator('[name=firstName]').fill('Fictional browser correction');
    await page.locator('#save-reason').fill('Rendered browser correction with real MFA session');
    const saved=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/connected/tax/inputs'&&r.request().method()==='POST');
    await page.locator('#save-input').click();assert.equal((await saved).status(),201);
    await page.waitForFunction(()=>!document.querySelector('#reopen-input').disabled);
    stage='tax-reload';
    await page.reload();await page.waitForFunction(()=>!document.querySelector('#reopen-input').disabled);
    await page.locator('#reopen-input').click();
    await page.waitForFunction(()=>document.querySelector('[name=firstName]')?.value==='Fictional browser correction');
    assert.equal(await page.locator('#saved-version option').count(),4);
    assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    stage='browser-logout';
    await page.goto(fixture.origin+'/connected.html');
    await page.locator('#logout').waitFor({state:'visible'});
    await page.locator('#logout').click();
    await page.locator('#login-panel').waitFor({state:'visible'});
    assert.equal((await context.request.get(fixture.origin+'/api/connected/tax/inputs?profile=orchard&business=business&year=2026')).status(),401);
    assert.deepEqual(errors,[]);
    console.log(JSON.stringify({rendered_reserve_choices_and_periods:'passed',rendered_records_confirmation_saved_and_invalidated:'passed',rendered_tax_save_reload_reopen:'passed',rendered_books_periods_documents_handoff:'passed',
      rendered_document_list_download_and_correction_choice:'passed',rendered_cash_explanation_amendment_persisted:'passed',rendered_payment_correction_preserves_unverified_original:'passed',rendered_entry_history_correction_choice:'passed',rendered_permitted_case_choice:'passed',rendered_foreign_scope_clears_data:true,rendered_logout_denies_tax:true,api_mocking:false,
      authentication:'actual browser password and OTP through HTTPS callback',browser_certificate_trust:'not verified; disposable self-signed fixture',
      browser_storage_empty:true,mobile_overflow:false,
      elapsed_seconds:Math.round((performance.now()-started)/100)/10,
      timing_scope:'single local fictional browser run, includes browser password/OTP; excludes fixture wait and runtime startup'}));
  }finally{await browser.close();}
})().catch(error=>{console.error('Rendered local MFA tax verification failed at '+stage+' '+(error.name==='TimeoutError'?'timeout':error.name==='AssertionError'?'assertion':(String(error.message).match(/net::ERR_[A-Z_]+/)||['operation'])[0]));process.exitCode=1;});
