'use strict';
// Sensitive profile values remain in this page's memory; no browser storage.
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dollars=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v);
const draft={profile:{},profileReady:false,forms:[],active:0,step:'profile',year:'2025',revision:0};
const catalog=[['1095-A','Marketplace health insurance'],['1098','Mortgage interest'],['1098-E','Student loan interest'],['1098-T','Tuition statement'],['1099-B','Broker transactions'],['1099-DIV','Dividends'],['1099-G','Government payments'],['1099-INT','Interest'],['1099-K','Payment transactions'],['1099-MISC','Miscellaneous information'],['1099-NEC','Nonemployee compensation'],['1099-OID','Original issue discount'],['1099-Q','Education distributions'],['1099-R','Retirement distributions'],['1099-S','Real estate proceeds'],['5498','IRA contributions'],['K-1 (1041)','Estate or trust beneficiary'],['K-1 (1065)','Partnership'],['K-1 (1120-S)','S corporation'],['RRB-1099','Railroad benefits'],['Schedule 1','Additional income and adjustments'],['Schedule 2','Additional taxes'],['Schedule 3','Additional credits and payments'],['Schedule C','Business income and expenses'],['Schedule E','Rentals and pass-through income'],['Schedule F','Farm income and expenses'],['SSA-1099','Social Security benefits'],['W-2','Wages and withholding'],['W-2G','Gambling winnings']].sort((a,b)=>a[0].localeCompare(b[0],'en',{numeric:true}));
function input(name,label,value='',attrs=''){return `<label>${label}<input name="${name}" value="${esc(value)}" ${attrs}></label>`;}
function activate(step){draft.step=step;document.querySelectorAll('[data-step]').forEach(b=>{b.classList.toggle('active',b.dataset.step===step);b.setAttribute('aria-current',b.dataset.step===step?'step':'false');});$('#side-actions').innerHTML='';}
function heading(text,sub){return `<h1 tabindex="-1">${text}</h1><p class="intro">${sub}</p>`;}
function focusHeading(){document.querySelector('main h1')?.focus({preventScroll:true});window.scrollTo(0,0);}
function profile(){activate('profile');const p=draft.profile;
  $('#content').innerHTML=heading('Let’s start with you.','Your information belongs at the top of your return. Enter it once, then match your documents.')+`<p class="quiet">Use fictional information in this preview. Entries stay in this page’s memory and clear when refreshed.</p><form id="profile-form"><div class="profile-grid">
  ${input('firstName','First name',p.firstName,'required autocomplete="off"')}${input('lastName','Last name',p.lastName,'required autocomplete="off"')}
  ${input('ssn','Social Security number',p.ssn,'type="password" inputmode="numeric" pattern="[0-9]{3}-?[0-9]{2}-?[0-9]{4}" required autocomplete="off" placeholder="000-00-0000"')}
  ${input('birthday','Date of birth',p.birthday,'type="date" required')}
  <div class="wide">${input('address','Street address',p.address,'required autocomplete="off"')}</div>
  ${input('city','City',p.city,'required')}${input('state','State (two-letter code)',p.state,'required maxlength="2" pattern="[A-Za-z]{2}"')}
  ${input('zip','ZIP code',p.zip,'required pattern="[0-9]{5}(-[0-9]{4})?" inputmode="numeric"')}
  <label>Filing status<select name="status"><option value="single">Single</option></select></label>
  </div><p class="quiet" style="margin-top:24px">This first working path supports a single filer’s Form 1040 with W‑2 income. Other filing statuses and Form 1041 are still being built.</p><div class="actions"><button class="primary" type="submit">Continue to your forms</button></div></form>`;
  const form=$('#profile-form');form.addEventListener('input',()=>{draft.profile=Object.fromEntries(new FormData(form));draft.profileReady=form.checkValidity();});
  form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;draft.profile=Object.fromEntries(new FormData(form));draft.profileReady=true;forms();});focusHeading();
}
function forms(){activate('forms');$('#content').innerHTML=heading('Click your form.','They are in alphabetical order first and numerical order where needed.')+`<label class="search">Find the form in your hand<input id="form-search" type="search" placeholder="Try W-2, 1099-R or Schedule C"></label><div id="catalog" class="catalog"></div><p class="quiet">W‑2 entry is available now. The other listed forms are the next work in progress. Document import is not available yet.</p>${draft.forms.length?'<button id="return-w2">Return to your W‑2</button>':''}`;
  const draw=()=>{const q=$('#form-search').value.toLowerCase().replace(/‑/g,'-');const items=catalog.filter(c=>c.join(' ').toLowerCase().includes(q));$('#catalog').innerHTML=items.length?items.map(([name,desc])=>`<button class="form-choice" data-form="${esc(name)}" ${name!=='W-2'?'disabled':''}><span><strong>${esc(name)}</strong><small>${esc(desc)}</small></span><small>${name==='W-2'?'Enter form':'In progress'}</small></button>`).join(''):'<p>No matching form in this preview.</p>';$('#catalog').querySelector('[data-form="W-2"]')?.addEventListener('click',()=>confirmW2(false));};
  $('#form-search').addEventListener('input',draw);draw();$('#return-w2')?.addEventListener('click',entry);focusHeading();
}
function confirmW2(another){activate('forms');$('#content').innerHTML=heading('You chose W‑2.','If this is the form in your hand, click Continue.')+`<div class="notice"><strong>W‑2 · Wage and Tax Statement</strong><p>Your employer sends this form to show your wages and taxes withheld.</p></div><div class="actions"><button id="confirm-w2" class="primary">Continue</button><button id="different-form">Choose a different form</button></div>`;$('#confirm-w2').onclick=()=>layouts(another);$('#different-form').onclick=forms;focusHeading();}
function mini(type){return `<div class="mini-document ${type==='stacked'?'stacked':''}" aria-hidden="true">${['Employer','1 Wages','2 Withheld','Employee','3 SS wages','4 SS tax','12 Codes','15 State','17 State tax'].map(t=>`<i>${t}</i>`).join('')}</div>`;}
function layouts(another=false,change=false){activate('forms');$('#content').innerHTML=heading('Which one looks like yours?','Choose the closest arrangement. The box numbers mean the same thing in either layout.')+`<div class="layout-options">${[['standard','Standard layout','Employer details on the left; amounts on the right.'],['stacked','Stacked layout','Employer and employee details above the amounts.']].map(([id,title,description])=>`<button class="layout-choice" data-layout="${id}">${mini(id)}<strong>${title}</strong><span class="quiet">${description}</span></button>`).join('')}</div><div class="actions"><button id="layout-back">Back</button></div>`;document.querySelectorAll('[data-layout]').forEach(b=>b.onclick=()=>{if(change){draft.forms[draft.active].layout=b.dataset.layout;}else{const p=draft.profile;draft.forms.push({layout:b.dataset.layout,employeeName:`${p.firstName||''} ${p.lastName||''}`.trim(),employeeAddress:`${p.address||''}\n${p.city||''}, ${p.state||''} ${p.zip||''}`.trim(),ssn:p.ssn||'',states:[{}],codes:[{},{},{},{}],checks:{}});draft.active=draft.forms.length-1;}entry();updateEstimate();});$('#layout-back').onclick=()=>change?entry():confirmW2(another);focusHeading();}
function box(key,num,label,type='text',cls=''){const f=draft.forms[draft.active];const attrs=type==='number'?'type="number" min="0" max="1000000000" step="0.01" inputmode="decimal"':'type="text"';return `<div class="box ${cls}"><label><b>${num}</b>${label}${type==='textarea'?`<textarea data-field="${key}" aria-label="${num} ${label}">${esc(f[key])}</textarea>`:`<input data-field="${key}" aria-label="${num} ${label}" value="${esc(f[key])}" ${attrs}>`}</label></div>`;}
function entry(){if(!draft.forms.length)return forms();activate('forms');const f=draft.forms[draft.active];
  $('#side-actions').innerHTML='<div class="action-stack"><button class="primary" id="side-next">Continue to state review</button><button id="side-add">Add another W‑2</button></div>';
  $('#side-next').onclick=stateReview;$('#side-add').onclick=()=>confirmW2(true);
  $('#content').innerHTML=heading('Put the numbers and information in exactly the same.','Match the boxes on your W‑2. Your estimate updates as you type.')+`<div class="documents">${draft.forms.map((x,i)=>`<button data-document="${i}" class="${i===draft.active?'active':''}">W‑2 ${i+1}${x.employerName?' · '+esc(x.employerName.slice(0,24)):''}</button>`).join('')}</div><div class="document-frame ${f.layout==='stacked'?'stacked-layout':''}"><div class="form-header"><h2>W‑2 · ${f.layout==='stacked'?'Stacked':'Standard'} layout</h2><button class="link" id="change-layout">Change layout</button></div><div class="w2-sheet"><div class="document-title"><strong>Form W‑2 · Wage and Tax Statement</strong><span>${esc(draft.year)} · Entry copy</span></div><div class="w2-grid">
  <div class="box identity">${input('unused','b Employer identification number (EIN)',f.ein,'data-field="ein"')}<label style="margin-top:12px">c Employer’s name, address and ZIP code<textarea data-field="employerName" aria-label="c Employer name and address">${esc(f.employerName)}</textarea></label>${input('unused','d Control number',f.control,'data-field="control"')}</div>
  ${box('box1','1','Wages, tips, other compensation','number')}${box('box2','2','Federal income tax withheld','number')}${box('box3','3','Social security wages','number')}${box('box4','4','Social security tax withheld','number')}${box('box5','5','Medicare wages and tips','number')}${box('box6','6','Medicare tax withheld','number')}
  <div class="box employee">${input('unused','a Employee’s Social Security number',f.ssn,'data-field="ssn" type="password" autocomplete="off"')}${input('unused','e Employee’s name',f.employeeName,'data-field="employeeName"')}<label style="margin-top:12px">f Employee’s address and ZIP code<textarea data-field="employeeAddress">${esc(f.employeeAddress)}</textarea></label></div>
  ${box('box7','7','Social security tips','number')}${box('box8','8','Allocated tips','number')}${box('box10','10','Dependent care benefits','number')}${box('box11','11','Nonqualified plans','number')}
  ${box('box14',draft.year==='2026'?'14a':'14','Other','textarea')}${draft.year==='2026'?box('box14b','14b','Treasury Tipped Occupation Code(s)'):''}<div class="box box12"><label><b>12</b>Codes and amounts</label><div class="codes">${f.codes.map((c,i)=>`<input data-code="${i}" aria-label="12${String.fromCharCode(97+i)} Code" value="${esc(c.code)}" maxlength="2"><input type="number" min="0" step="0.01" data-code-amount="${i}" aria-label="12${String.fromCharCode(97+i)} Amount" value="${esc(c.amount)}">`).join('')}</div></div><div class="box checks"><label><b>13</b>Checkboxes</label>${[['statutory','Statutory employee'],['retirement','Retirement plan'],['sick','Third-party sick pay']].map(([key,label])=>`<label>${label}<input type="checkbox" data-check="${key}" ${f.checks[key]?'checked':''}></label>`).join('')}</div>
  </div><div class="state-rows" id="state-rows"></div></div><p class="quiet" style="margin:12px 0 0">Boxes 1 and 2 update this federal scenario. Other boxes are captured for later review; their tax treatment is not implemented yet.</p></div><div class="actions"><button class="primary" id="state-next">Continue to state review</button><button id="another-w2">Add another W‑2</button><button id="remove-w2">Remove this W‑2</button></div>`;
  drawStates();$('#content').querySelectorAll('[data-field]').forEach(el=>el.addEventListener('input',()=>{f[el.dataset.field]=el.value;if(['box1','box2'].includes(el.dataset.field))scheduleEstimate();}));$('#content').querySelectorAll('[data-code]').forEach(el=>el.oninput=()=>{f.codes[+el.dataset.code].code=el.value;});$('#content').querySelectorAll('[data-code-amount]').forEach(el=>el.oninput=()=>{f.codes[+el.dataset.codeAmount].amount=el.value;});$('#content').querySelectorAll('[data-check]').forEach(el=>el.onchange=()=>{f.checks[el.dataset.check]=el.checked;});document.querySelectorAll('[data-document]').forEach(b=>b.onclick=()=>{draft.active=+b.dataset.document;entry();});$('#change-layout').onclick=()=>layouts(false,true);$('#another-w2').onclick=()=>confirmW2(true);$('#state-next').onclick=stateReview;$('#remove-w2').onclick=()=>{draft.forms.splice(draft.active,1);draft.active=Math.max(0,draft.active-1);entry();updateEstimate();};focusHeading();
}
function drawStates(){const f=draft.forms[draft.active];$('#state-rows').innerHTML=f.states.map((row,i)=>`<div class="state-row">${[['state','15 State'],['id','Employer state ID'],['wages','16 State wages'],['tax','17 State tax'],['localWages','18 Local wages'],['localTax','19 Local tax'],['locality','20 Locality']].map(([key,label])=>`<label>${label}<input data-state-row="${i}" data-state-key="${key}" aria-label="${label} row ${i+1}" value="${esc(row[key])}" ${['wages','tax','localWages','localTax'].includes(key)?'type="number" min="0" step="0.01"':key==='state'?'maxlength="2"':''}></label>`).join('')}<button data-remove-state="${i}" aria-label="Remove state row ${i+1}">×</button></div>`).join('')+'<button class="link add-state" id="add-state">+ Add another state row</button>';$('#add-state').onclick=()=>{f.states.push({});drawStates();};document.querySelectorAll('[data-state-row]').forEach(el=>el.oninput=()=>{f.states[+el.dataset.stateRow][el.dataset.stateKey]=el.value;});document.querySelectorAll('[data-remove-state]').forEach(b=>b.onclick=()=>{f.states.splice(+b.dataset.removeState,1);drawStates();});}
let estimateTimer;
function scheduleEstimate(){draft.revision++;clearTimeout(estimateTimer);$('#estimate-result').innerHTML='<strong class="estimate-number">…</strong><h3>Updating estimate</h3>';estimateTimer=setTimeout(updateEstimate,180);}
async function updateEstimate(){const revision=++draft.revision;try{const response=await fetch('/api/return/estimate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tax_year:draft.year,filing_status:'single',w2s:draft.forms.map(f=>({box1:f.box1??'',box2:f.box2??''}))})});const r=await response.json();if(revision!==draft.revision)return;if(!response.ok)throw Error(r.error||'Check the amounts in boxes 1 and 2.');draft.estimate=r;$('#sum-wages').textContent=dollars(r.wages);$('#sum-tax').textContent=dollars(r.estimated_tax);$('#sum-withholding').textContent=dollars(r.withholding);$('#estimate-result').innerHTML=draft.forms.length?`<strong class="estimate-number ${r.balance_due?'owing':''}">${dollars(r.balance_due||r.refund)}</strong><h3>${r.balance_due?'Estimated balance due':'Estimated refund'}</h3>${r.incomplete?'<p class="quiet">Still entering information · Blank boxes currently count as zero.</p>':''}`:'<strong class="estimate-number">—</strong><h3>Enter your W‑2 to begin</h3>';withholdingHelp(r);}catch(error){if(revision!==draft.revision)return;draft.estimate=null;$('#estimate-result').innerHTML=`<h3>Estimate unavailable</h3><p class="error">${esc(error.message)}</p>`;['#sum-wages','#sum-tax','#sum-withholding'].forEach(id=>$(id).textContent='—');$('#withholding-help').innerHTML='';}}
function withholdingHelp(r){$('#withholding-help').innerHTML=r.balance_due?`<div class="withholding"><h3>Planning ahead</h3><p>A balance can mean too little federal tax was withheld. Once all income and credits are reviewed, use the IRS withholding estimator to update your W‑4.</p><a href="https://www.irs.gov/individuals/tax-withholding-estimator" target="_blank" rel="noopener">IRS withholding estimator</a><p>This incomplete scenario is not enough to recommend a W‑4 amount.</p></div>`:'';}
function stateReview(){if(!draft.forms.length)return forms();activate('state');const states=[...new Set(draft.forms.flatMap(f=>f.states.map(s=>(s.state||'').toUpperCase())).filter(Boolean))];$('#content').innerHTML=heading('Verify your state.','Your state may need a few different things. Let’s first check where you lived and worked.')+`<p>States on your W‑2s: <strong>${esc(states.join(', ')||'No states entered yet')}</strong></p><div class="profile-grid">${input('residence','Where did you live? (state)',draft.profile.state,'id="residence-state" maxlength="2"')}<label>Did you move between states this year?<select id="state-move" aria-label="Did you move between states this year?"><option value="">Choose an answer</option><option>No</option><option>Yes</option></select></label><label>Did you work in a different state?<select id="state-work" aria-label="Did you work in a different state?"><option value="">Choose an answer</option><option>No</option><option>Yes</option></select></label></div><div class="notice" style="margin-top:24px"><strong>State calculation is still being built.</strong><p>These answers are collected for review. No state refund or balance has been calculated.</p></div><div class="actions"><button class="primary" id="review-next">Continue to review</button><button id="back-w2">Back to W‑2</button></div>`;for(const id of ['residence-state','state-move','state-work']){const el=$('#'+id);el.value=draft.stateAnswers?.[id]??el.value;el.onchange=()=>{draft.stateAnswers={...(draft.stateAnswers||{}),[id]:el.value};};}$('#review-next').onclick=review;$('#back-w2').onclick=entry;focusHeading();}
function review(){if(!draft.forms.length)return forms();activate('review');$('#content').innerHTML=heading('Review what you’ve entered.','You can return to any W‑2 and make a correction. Your estimate will update.')+`<p>${esc(draft.profile.firstName)} ${esc(draft.profile.lastName)} · Single · Tax year ${esc(draft.year)}</p><table class="review-table"><caption>W‑2 amounts entered so far</caption><thead><tr><th scope="col">Document</th><th scope="col">Box 1 wages</th><th scope="col">Box 2 withholding</th><th scope="col">Action</th></tr></thead><tbody>${draft.forms.map((f,i)=>`<tr><td>W‑2 ${i+1}<br>${esc(f.employerName||'Employer not entered')}</td><td>${esc(f.box1||'Blank')}</td><td>${esc(f.box2||'Blank')}</td><td><button data-edit="${i}">Edit</button></td></tr>`).join('')}</tbody></table><div class="notice"><strong>Your return is not ready to file.</strong><p>Credits, additional W‑2 tax treatment, other income, state calculations, IRS form export and filing checks still need implementation. Payment, refund transfer, investment routing and signatures are not available.</p></div><button id="review-add">Add another W‑2</button>`;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{draft.active=+b.dataset.edit;entry();});$('#review-add').onclick=()=>confirmW2(true);focusHeading();}
document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{if(b.dataset.step==='profile')return profile();if(!draft.profileReady)return profile();({forms,state:stateReview,review})[b.dataset.step]();});
$('#tax-year').onchange=e=>{draft.year=e.target.value;updateEstimate();if(draft.step==='forms'&&draft.forms.length)entry();else if(draft.step==='review')review();};
profile();
